### ISSUE TITLE
Concurrent user number on a single host is too low

### ISSUE THREAD

**Issue by ish91** [damies13/rfswarm#146]
Hi,
I use the following libraries in the robot file:

- RPA.JSON
- OperatingSystem
- RequestsLibrary

The test reads a JSON file first and then sends its content to the designated endpoint.
**The problem is, that the agent host reaches 100% CPU load when there are only 8 concurrent users**. This is a terrible bottleneck since this number is too low to load test the endpoint (not speaking of stress testing...)
I tried running the agent on different platforms (ubuntu 22, windows 10) but that did not solve this issue.
The hardware should be enough:

- 4-core CPU
- 8GB RAM

The JSON file that is being read every time is somewhat bigger (59KB) and the response is around 20KB, but I cannot shrink them...

Could you help me solve this issue, please?

Thanks in advance!

**Comment by damies13** [comment]
Hi,

How much [Think Time](https://github.com/damies13/rfswarm/blob/master/Doc/Preparing_for_perf.md#think-time) do you have in your test case? 

Also do you have the do you have the RequestsLibrary calls in a loop to be called numerous times?

While RequestsLibrary is much lower overhead than other libraries, there is still some overhead in launching robot and loading the libraries so if you only have a single RequestsLibrary all in your test with no think time, then that would explain your situation.

If you only have a single RequestsLibrary call, then it might be a good idea to put a loop around that call and also add a sleep (even if it's just 0.01 seconds) and have the loop enough times to run the test at least a minute, but longer would be better, then it gives the OS a chance to run other robots.

As you'll probably want the time for the single RequestsLibrary call in your results the [Keywords](https://github.com/damies13/rfswarm/blob/master/Doc/Preparing_for_perf.md#keywords) of the same page covers how to control the name displayed for custom keywords in the results, I'd suggest putting the RequestsLibrary call in a Keyword and putting the Keyword and sleep in the loop so the sleep time is not included in the keyword's time.

For reference I've run ~300 robots with requests library using a first gen Mackbook Air (recycled hardware) with only 4GB Ram, it was not memory limited buy CPU, but the test cases had several think times in their loops of ~30 seconds.

The test cases I used are here [TestDataTable-API_requests_perf.robot](https://github.com/damies13/TestDataTable/blob/master/Regression_Tests/TestDataTable-API_requests_perf.robot), about 100 robots each of:
- Get Hold Return Value BNE
- Get Hold Return Value GC
- Data cycle test

I should note that if you run without any think time/sleep/pacing in other performance test tools then you would have the same CPU limit at around 8 users running as well, your CPU only has 4 cores and with hyper-threading giving you 8 threads or virtual CPU's, so this is a limit of the hardware and the lack of sleep time (constantly busy process) rather than a tool issue. 

Hope that helps,

Dave.

**Comment by damies13** [comment]
I guess by no comment since May this is answered, will close for now.
